[package]
name = "racr"
version = "0.1.0"
edition = "2018"

description = "Rust types for Register Access Code for Rust (RACR) format"
license = "Apache-2.0/MIT"

authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]

[dependencies]
